---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gaming
  template:
    metadata:
      labels:
        app: gaming
    spec:
      containers:
      - name: application-container
        image: saikumar1817/tetris-game:version-4.0
        ports:
        - containerPort: 3000 
